### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by joonsu0109gh** [geometriczoom/two-plane-prior#1]
Will your full training code be made available?

**Comment by anuragxel** [comment]
Hi sorry for the late response. This code release is modelled closely to Fovea's and uses mmdetection, you can use the trainer provided in mmdet (tools/train.py) or Fovea's codebase to train the model yourself, just like how you would train any mmdet model.

**Comment by joonsu0109gh** [comment]
Thank you for the kind answer. :)
